Initial branch
WildCodeSchool-2024-02/php-poec-paris-p2-quickquery pull request #1
Opened 2024-05-29 07:38 UTC by nasbous

Initial branch push has been group validated, please review in order to let us continue.

Thank you <3.

2024-05-29 07:40 UTC, AxelMlz approved these changes

2024-05-29 07:45 UTC, pierrealain74 approved these changes
magnifico!

2024-05-29 08:02 UTC, mickaellambert requested changes

2024-05-29 08:02 UTC, mickaellambert commented on config/db.php.dist
> +define('APP_DB_NAME', 'qq');
Je prefererai un nom plus parlant, "quickquery" me parait mieux

2024-05-29 08:02 UTC, mickaellambert commented on database.sql
> +  `descrption` varchar(255) NOT NULL,
attention, petite erreur de typo ici, le champ devrait s'appeler "description" et même plus logiquement, je l'appelerai "content" et je ne le limiterai pas à 255 caractères donc je lui donnerai le type TEXT

2024-05-29 08:02 UTC, mickaellambert commented on database.sql
> +  `createed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
Attention à la typo aussi ici "created_at"

2024-05-29 08:02 UTC, mickaellambert commented on database.sql
> +  ADD CONSTRAINT `alert_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
Je ne vous conseille pas de mettre des critères de contraintes de suppression ou d'update en cascade, ça va vous poser des problemes lorsque vous allez faire des US de suppression ou de mise à jour. 
Pour l'instant, ajoutez simplement les contraintes de clé étrangères si vous avez envie (et c'est pas obligatoire)

2024-05-29 08:02 UTC, mickaellambert commented on public/assets/css/style.css
> +    color: black;
Pas sur que votre background doit être noir sur votre appli, je pense que c'est un oubli de test

2024-05-29 08:02 UTC, mickaellambert commented on public/index.php
C'est bizarre de m'envoyer une modification sur le controleur frontal, je comprends pas trop ce qui a été fait ici. Est ce que le contenu de ce fichier est toujours présent ? Si oui c'est ok mais faites attention aux modifs que vous envoyez

2024-05-29 08:02 UTC, mickaellambert commented on src/Controller/AbstractController.php
Pareil pour l'AbastractController, aucune modification n'aurait du être effectuée sur ce fichier

2024-05-29 08:02 UTC, mickaellambert commented on src/View/Home/index.html.twig
> +    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus maxime illum quidem repellendus esse. Inventore non dicta consequatur neque possimus quasi, error excepturi laudantium obcaec
Pas de Lorem Ipsum dans les PR, j'aurai la modification de ce fichier lorsque vous serez sur l'US concernant la home page de votre application

2024-05-29 10:04 UTC, mickaellambert requested changes

2024-05-29 10:04 UTC, mickaellambert commented on database.sql
> +  `description` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
Passer le champ en typage TEXT et si vous avez envie, le renommer "content"

2024-05-30 12:44 UTC, mickaellambert requested changes

2024-05-30 12:44 UTC, mickaellambert commented on database.sql
> +(1, 'Pierre', 'jobrider@gmail.com', '123456'),
Ici, il faudrait hasher les mots de passes comme vu hier grâce à la fonction password_hash()

2024-05-30 22:12 UTC, mickaellambert approved these changes

2024-05-30 22:12 UTC, merged