S1US03 Alert Question
WildCodeSchool-2024-02/php-poec-paris-p2-quickquery pull request #5
Opened 2024-06-05 13:47 UTC by pierrealain74

A user can add an alert for a question

2024-06-06 13:46 UTC, mickaellambert requested changes

2024-06-06 13:46 UTC, mickaellambert commented on src/Controller/QuestionController.php
> +    public function addQuestion(): ?string
Ici, appeler la route "add"

2024-06-06 13:46 UTC, mickaellambert commented on src/Controller/QuestionController.php
> +    public function addAlert(): string
Ici, appeler la route "alert"

2024-06-06 13:46 UTC, mickaellambert commented on src/routes.php
> +    'add-question' => ['QuestionController', 'addQuestion',],
Ici `'question/add' => ['QuestionController', 'add',],`

2024-06-06 13:46 UTC, mickaellambert commented on src/routes.php
> +    'add-alert' => ['QuestionController', 'addAlert',],
Ici `'question/alert' => ['QuestionController', 'alert',],`

2024-06-06 13:46 UTC, mickaellambert commented on src/Controller/QuestionController.php
> +        $alertManager = new AlertManager();
```
public function alert(): string 
{
    $questionId = htmlentities(trim($_POST['questionId']));

    \\ TODO update $userId when login is completed
    $userId = 1;

    $alertManager = new AlertManager();
    $alertManager->insert($userId, $questionId);

    header('Location: /?f=1');
}
```

2024-06-06 13:46 UTC, mickaellambert commented on src/Model/AlertManager.php
> +            $statement = $this->pdo->prepare(
Trop d'indentation

2024-06-06 21:26 UTC, mickaellambert requested changes
Attention, ta PR n'a pas passé tous les tests de qualité de code (croix rouge sur la PR), regarde en détail ce qu'il te dit et corrige le stp !

2024-06-06 21:26 UTC, mickaellambert commented on src/Controller/QuestionController.php
> +            $question = $_POST;
pourquoi ne pas juste faire un `$question = array_map('htmlentites', array_map('trim', $_POST));` ?

2024-06-07 06:33 UTC, pierrealain74 commented on src/Controller/QuestionController.php
> +            $question = $_POST;
Parce qu'il ya deux tableaux (les tags et heures qui sont des des select), j'ai donc pensé que ce n'etait pas necessaire

2024-06-07 06:45 UTC, pierrealain74 commented on src/Controller/QuestionController.php
> +            $question = $_POST;
et on peux pas trimer un array, ca doit petre un string, du coup on doit encore faire une autre boucle de chaque tableau

2024-06-07 10:14 UTC, merged