S2US05-inscription
WildCodeSchool-2024-02/php-poec-paris-p2-quickquery pull request #8
Opened 2024-06-06 14:25 UTC by Kay-N9

Création du Usermanager et des controller Inscription et log, en plus de quelques routes et du twig.

2024-06-06 21:36 UTC, mickaellambert requested changes

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
Tu pourrais faire un seul controller que tu appellerais `UserController` qui contiendrait la méthode `register` et la méthode `login` plutôt que de séparer en deux controller

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
> +    public function add(): ?string
A renommer en `register` du coup

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
> +
Attention aux sauts de lignes inutiles

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
> +        $userManager = new UserManager();
Cette ligne pourrait être dans le if du dessous, pas besoin d'instancier un manager si nous ne sommes pas en méthode post

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
> +            $inscription = $_POST;
`$user = array_map('htmlentities', array_map('trim', $_POST));`

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
> +            foreach ($inscription as $key => $value) {
Pas besoin de faire cette boucle du coup

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
> +
saut de ligne inutile

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/InscriptionController.php
> +    private function validate(array $inscription)
`private function validate(array $user)`

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/LogController.php
> +    public function processLogin(): ?string
`login()`

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/LogController.php
> +use password_hash;
Pas besoin de ça

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/LogController.php
> +use session_start;
Le `session_start()` va aller dans le controleur frontal plutôt qu'ici, comme ça à chaque requête, la session serait initiée

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/LogController.php
> +                session_start();
a mettre dans le controleur frontal du coup

2024-06-06 21:36 UTC, mickaellambert commented on src/Controller/QuestionController.php
Pourquoi supprimer ce fichier ? :o

2024-06-06 21:36 UTC, mickaellambert commented on src/Model/QuestionManager.php
Pourquoi supprimer ce fichier ? :o

2024-06-06 21:36 UTC, mickaellambert commented on src/Model/UserManager.php
> +    public function emailExists(string $email)
`selectOneByEmail` plutôt et retourne toutes les données de l'utilisateur plutôt que le count, ça pourrait peut être servir plus tard

2024-06-06 21:36 UTC, mickaellambert commented on src/Model/UserManager.php
> +    public function getByEmail(string $email): array
Ah bah elle est là, parfait, utilise celle la pour checker si un utilisateur existe déjà

2024-06-06 21:36 UTC, mickaellambert commented on src/routes.php
> +    'inscription' => ['InscriptionController', 'add',],
`register` plutôt que `inscription`

2024-06-06 21:36 UTC, mickaellambert commented on src/routes.php
> +    'index' => ['LogController', 'logout',],
`logout` plutôt que `index`

2024-06-10 10:31 UTC, mickaellambert requested changes

2024-06-10 10:31 UTC, mickaellambert commented on src/Model/QuestionManager.php
> +/*         $statement = $this->pdo->query("
Commentaires inutiles

2024-06-10 10:31 UTC, mickaellambert commented on src/View/Question/add.html.twig
> -{% endblock %}
C'est voulu de supprimer tout ça du questionnaire d'ajout de question ?

2024-06-10 10:31 UTC, mickaellambert commented on src/View/User/Inscription.html.twig
Pas de majuscule sur le nom des fichiers des vues

2024-06-10 13:42 UTC, Kay-N9 commented on src/View/Question/add.html.twig
> -{% endblock %}
il est dans le twig _form

2024-06-12 13:16 UTC, merged